import { useEffect, useRef, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import confetti from "canvas-confetti";
import api from "../api/client.js";
import { computeLeaderboard } from "../utils/scoring.js";
import GlassCard from "../components/ui/GlassCard.jsx";
import Podium from "../components/Podium.jsx";
import Scoreboard from "../components/Scoreboard.jsx";
import useOlympicStore from "../store/useOlympicStore.js";

export default function WinnerPage() {
  const { code } = useParams();
  const navigate = useNavigate();
  const { olympic: storeOlympic, leaderboard: storeLeaderboard } =
    useOlympicStore();

  const [olympic, setOlympic] = useState(storeOlympic);
  // Prefer finalLeaderboard snapshot from store if available
  const [leaderboard, setLeaderboard] = useState(
    storeOlympic &&
      Array.isArray(storeOlympic.finalLeaderboard) &&
      storeOlympic.finalLeaderboard.length > 0
      ? storeOlympic.finalLeaderboard
      : storeLeaderboard,
  );
  const [loading, setLoading] = useState(!storeOlympic);
  const [copied, setCopied] = useState(false);
  const [showBonusLog, setShowBonusLog] = useState(false);

  const confettiFired = useRef(false);

  // Fetch from API if not in store
  useEffect(() => {
    if (!storeOlympic && code) {
      api
        .get(`/olympics/${code.toUpperCase()}`)
        .then(({ data }) => {
          setOlympic(data);
          // Use persisted finalLeaderboard if available, otherwise compute
          setLeaderboard(
            Array.isArray(data.finalLeaderboard) &&
              data.finalLeaderboard.length > 0
              ? data.finalLeaderboard
              : computeLeaderboard(data),
          );
        })
        .catch(() => navigate("/"))
        .finally(() => setLoading(false));
    }
  }, [code]);

  // Fire confetti on mount
  useEffect(() => {
    if (!confettiFired.current && leaderboard.length > 0) {
      confettiFired.current = true;
      const duration = 3000;
      const end = Date.now() + duration;

      const frame = () => {
        confetti({
          particleCount: 5,
          angle: 60,
          spread: 55,
          origin: { x: 0 },
          colors: ["#8b5cf6", "#ec4899", "#22d3ee", "#facc15"],
        });
        confetti({
          particleCount: 5,
          angle: 120,
          spread: 55,
          origin: { x: 1 },
          colors: ["#8b5cf6", "#ec4899", "#22d3ee", "#facc15"],
        });
        if (Date.now() < end) requestAnimationFrame(frame);
      };
      frame();
    }
  }, [leaderboard]);

  function copyResults() {
    const winner = leaderboard[0];
    const text = [
      `🏅 ${olympic?.name} — Final Results`,
      "",
      ...leaderboard.map(
        (p, i) =>
          `${["🥇", "🥈", "🥉"][i] || `${i + 1}.`} ${p.name} — ${p.total} pts (${p.wins} wins)`,
      ),
      "",
      `Generated by Party Olympiade`,
    ].join("\n");

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-muted animate-pulse">Loading results…</div>
      </div>
    );
  }

  if (!olympic) return null;

  const scoringEnabled = olympic.scoringEnabled !== false;
  const winner = leaderboard[0];
  const allBonusLogs = leaderboard.flatMap((p) =>
    (p.bonusLog || []).map((log) => ({ player: p.name, ...log })),
  );

  // No-score view
  if (!scoringEnabled) {
    return (
      <div className="min-h-screen px-4 py-10">
        <div className="max-w-2xl mx-auto space-y-8">
          <div className="text-center animate-fade-in">
            <h1 className="text-4xl sm:text-5xl font-black text-white mb-2">
              🎉 Event Complete!
            </h1>
            <p className="text-muted">{olympic.name}</p>
          </div>

          <GlassCard>
            <h2 className="font-bold text-white mb-4">
              Participants ({olympic.participants.length})
            </h2>
            <div className="space-y-2">
              {olympic.participants.map((p) => (
                <div
                  key={p.name}
                  className="flex items-center gap-3 py-2 border-b border-white/5"
                >
                  {p.avatarBase64 ? (
                    <img
                      src={p.avatarBase64}
                      alt={p.name}
                      className="w-10 h-10 rounded-full object-cover"
                    />
                  ) : (
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-purple to-pink flex items-center justify-center font-bold text-white">
                      {p.name[0]}
                    </div>
                  )}
                  <span className="font-medium text-white">{p.name}</span>
                </div>
              ))}
            </div>
          </GlassCard>

          <div className="flex flex-col sm:flex-row gap-3 pb-8">
            <button
              className="btn-primary flex-1"
              onClick={() => navigate("/create")}
            >
              🚀 New Olympic
            </button>
            <button className="btn-ghost flex-1" onClick={() => navigate("/")}>
              🏠 Home
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen px-4 py-10">
      <div className="max-w-2xl mx-auto space-y-8">
        {/* Hero */}
        <div className="text-center animate-fade-in">
          <h1 className="text-4xl sm:text-5xl font-black text-white mb-2">
            🏆 Olympic Champion!
          </h1>
          <p className="text-muted">{olympic.name}</p>
        </div>

        {/* Winner highlight */}
        {winner && (
          <div
            className="glass rounded-2xl p-6 text-center shadow-[0_0_40px_rgba(139,92,246,0.15)]"
            style={{
              background:
                "linear-gradient(135deg, rgba(250,204,21,0.12), rgba(245,158,11,0.06)), linear-gradient(138deg, rgba(18,18,36,0.85), rgba(28,28,56,0.6))",
            }}
          >
            {leaderboard[0]?.name &&
            olympic.participants.find((p) => p.name === leaderboard[0].name)
              ?.avatarBase64 ? (
              <img
                src={
                  olympic.participants.find(
                    (p) => p.name === leaderboard[0].name,
                  ).avatarBase64
                }
                alt={winner.name}
                className="w-24 h-24 rounded-full object-cover border-4 border-yellow-400/60 mx-auto mb-4 shadow-xl"
              />
            ) : (
              <div className="w-24 h-24 rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 flex items-center justify-center text-5xl font-black mx-auto mb-4 shadow-xl">
                {winner.name[0]?.toUpperCase()}
              </div>
            )}
            <h2 className="text-3xl font-black text-yellow-400 mb-1">
              {winner.name}
            </h2>
            <p className="text-white font-bold">
              {winner.total} points · {winner.wins} wins
            </p>
          </div>
        )}

        {/* Podium */}
        <div className="pt-4">
          <Podium
            leaderboard={leaderboard}
            participants={olympic.participants}
          />
        </div>

        {/* Full leaderboard */}
        <GlassCard>
          <h2 className="font-bold text-white mb-4">Final Standings</h2>
          <Scoreboard
            leaderboard={leaderboard}
            participants={olympic.participants}
          />
        </GlassCard>

        {/* Bonus log */}
        {allBonusLogs.length > 0 && (
          <GlassCard>
            <button
              className="flex items-center justify-between w-full"
              onClick={() => setShowBonusLog((s) => !s)}
            >
              <h2 className="font-bold text-white">Bonus / Penalty Log</h2>
              <span className="text-muted text-sm">
                {showBonusLog ? "▲" : "▼"}
              </span>
            </button>
            {showBonusLog && (
              <div className="mt-3 space-y-1.5">
                {allBonusLogs.map((log, i) => (
                  <div
                    key={i}
                    className="flex items-center gap-2 text-sm py-1.5 border-b border-white/5"
                  >
                    <span className="font-medium text-white w-24 truncate">
                      {log.player}
                    </span>
                    <span className="text-muted flex-1">
                      {log.game} — {log.reason}
                    </span>
                    <span
                      className={`font-bold ${log.delta > 0 ? "text-green-400" : "text-pink-400"}`}
                    >
                      {log.delta > 0 ? `+${log.delta}` : log.delta}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </GlassCard>
        )}

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-3 pb-8">
          <button className="btn-primary flex-1" onClick={copyResults}>
            {copied ? "✅ Copied!" : "📋 Copy Results"}
          </button>
          <button
            className="btn-secondary flex-1"
            onClick={() => navigate("/create")}
          >
            🚀 New Olympic
          </button>
          <button className="btn-ghost flex-1" onClick={() => navigate("/")}>
            🏠 Home
          </button>
        </div>
      </div>
    </div>
  );
}
